---
- name: update cache
  apt: update_cache=yes

- name: install php5-mysql
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-cli
    - libapache2-mod-php5
    - php5-curl
  notify:
    - php5 installed
